def COLOR_MAP = [
    'SUCCESS' : 'good' ,
    'FAILURE' : 'danger' ,
]

pipeline {
    agent any 
    
    environment {
       cluster = "vprofileprodcluster"
       service = "	vproappservice"
    }

satges {
    stage('Deploy to prod ecs') {
        steps {
            withAWS(credentials: 'awscreds', region: 'us-east-1'){
                sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
            }
        }
    }
}
post{
        always {
            echo 'slack Notifications.'
            slackSend channel: '#ci-cd-pipeline' ,
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n more info at: ${env.BUILD_URL}"
        }
    }
}
